exclude: "^docs/|/migrations/|devcontainer.json|^CHANGELOG.md$"
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]

default_language_version:
  python: python3.10

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autofix_commit_msg: "ci: auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
  autoupdate_branch: develop
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  # pre-commit hooks #

  # Security & credential scanning/alerting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-ast

  # Formatters that may modify source files automatically
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args: ["--config", "package.json"]
        exclude_types: [html]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.5"
    hooks:
      - id: ruff-format
        name: ruff (format)
        args: ["."]

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.17.0"
    hooks:
      - id: django-upgrade
        args: ["--target-version", "5.0"]

  # Linters and validation
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.5"
    hooks:
      # Linter
      - id: ruff
        name: ruff (lint)
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --output-format=full

  - repo: https://github.com/djlint/djLint
    rev: "v1.34.1"
    hooks:
      - id: djlint-django

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # commit-msg hooks #

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
