#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

NUM_WORKERS=3
TIMEOUT=120
LOGLEVEL=info

if [ "$SERVER_DEBUG" == "true" ]; then
    LOGLEVEL=debug;
fi

python /app/src/manage.py collectstatic --clear --noinput

python -m gunicorn config.asgi \
    --chdir=/app/src \
    -k uvicorn.workers.UvicornWorker \
    --log-file - \
    --bind 0.0.0.0:8000 \
    --log-level $LOGLEVEL \
    --workers $NUM_WORKERS \
    --timeout $TIMEOUT
