#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

DJANGO_SUPERUSER_PASSWORD=test DJANGO_SUPERUSER_EMAIL=admin@local.lan \
    poetry run /app/src/manage.py createsuperuser --noinput || true

poetry run /app/src/manage.py runserver_plus 0.0.0.0:8000
